// src/utils/categories.js

const categories = [
  "Cement",
  "Plan & Design",
  "Furniture Carpenter Works",
  "Elevation",
  "Reinforcent Bars",
  "Borewells",
  "Health Monitoring",
  "Form Works",
  "Paints&Works",
  "Interiors",
  "Exteriors",
  "Trucks",
  "Vastu",
  "Labours",
  "Mason",
  "RMC",
  "Bricks",
  "Sand",
  "Aggregates",
  "Earth Movers",
  "Bull Dozers",
  "Water Tankers",
  "Surveyors",
  "Real Estates",
  "Legal Guidance",
  "Plumbing",
  "Electricals",
  "Elevator Works",
  "Tiles & Marbles",
  "Material Testing",
  "Contractors",
  "Ground Improvement Works",
  "DPC Works",
  "GIT Works",
  "Roads & Pavements",
  "Morrum (Red sand)",
  "Dismantal",
  "Granite Stones",
  "Cranes & Lifters",
  "Dust (Bore)",
  "Revits Software Works",
  "STAAD Pro Works",
  "Augumented Reality",
  "Destruction works",
  "GIS",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
];

export default categories;
