// src/utils/categories.js

const categories = [
  "Cement",
  "Plan & Design",
  "Furniture Carpenter Works",
  "Elevation",
  "Reinforcent Bars",
  "Borewells",
  "Health Monitoring",
  "Foam Works",
  "Paints&Works",
  "Interiors",
  "Exteriors",
  "Trucks",
  "Vastu",
  "Labours",
  "Mason",
  "RMC",
  "Bricks",
  "Sand",
  "Aggregates",
  "Earth Movers",
  "Bull Dozers",
  "Water Tankers",
  "Surveyors",
  "Real Estates",
  "Legal Guidance",
  "Plumbing",
  "Electricals",
  "Elevator Works",
  "Tiles & Marbles",
  "Material Testing",
  "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
  // "Contractors",
];

export default categories;
